server:
  port: 8080
spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: demo
  http:
      encoding:
        charset: UTF-8
        force: true
  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
  jackson:
      default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
#分页pageHelper
pagehelper:
  helper-dialect: mysql  #配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  reasonable: false #分页参数合理化功能，默认是false。 #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页； #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  support-methods-arguments: true #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
person:
  name: oneStar
  age: 18