server:
  port: 8080
spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: demo
  http:
      encoding:
        charset: UTF-8
        force: true
  jackson:
      default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*Person.xml
  type-aliases-package: com.example.demo.entity
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
